### PR TITLE
Feature/file api

### PR DESCRIPTION
**Pull request by swordensen**
Hi guys, 

This is my idea for the solutions to https://github.com/SHIV5T3R/Maestro/issues/1

Basically it just wraps the `react-native-fs` package with an easy to use FM handle. 

Ideally we will be able to use it as easily as:

```ts
import FM from 'src/fileManagement'

await FM.createFile('yourNewFile.txt');
```

Since we need a UI to set up E2E tests I mocked the react-native-fs API with node-fs. 

I have written several tests but, there are a few more that I need to handle. You can run the tests yourself with `yarn test`

Finally, dont forget to `yarn install`!

### CODE REVIEW

**Comment by dmtry-krachkovi** [comment]
This is the ideal solution, but we agreed already on trying to write the functionality ourselves and use minimal third-party solutions.

**Review by maxovicsteiner — CHANGES_REQUESTED** [review]
renameFile functionality missing

**Review by maxovicsteiner — APPROVED** [review]
Looks good! We can always finish the tests later

**Review by jaybuurdd — APPROVED** [review]
👍

**Review by Magrid0 — APPROVED** [review]
Looks good to me

**Pull request closed without merging**
